import type { Catalog, Locale, Translator } from '@autotranslate/core';
import { createTranslator, WIRE_FORMAT_VERSION } from '@autotranslate/core';
import type { CatalogModule, GetTOptions } from './types';
import { LOCALE_HEADER } from './types';

// Wire format this build was compiled against. Cross-checked against the
// loaded core at first `getT` call so a transitive version skew throws
// instead of corrupting the runtime. Bump in lockstep with core.
const EXPECTED_CORE_WIRE_FORMAT = 2;

let handshakeChecked = false;
function assertVersionHandshake(): void {
  if (handshakeChecked) return;
  handshakeChecked = true;
  if (WIRE_FORMAT_VERSION !== EXPECTED_CORE_WIRE_FORMAT) {
    throw new Error(
      `[autotranslate] version mismatch: @autotranslate/next expects ` +
        `@autotranslate/core wire format ${EXPECTED_CORE_WIRE_FORMAT}, but the loaded core ` +
        `reports ${WIRE_FORMAT_VERSION}. Pin both packages to the same release.`,
    );
  }
}

// WeakMap so a catalog module dropped by the app can be GC'd with its memo.
let moduleCache = new WeakMap<CatalogModule, Map<Locale, Promise<Catalog>>>();

/** Clear the in-process catalog memo. Useful in tests or after a hot reload. */
export function clearCatalogCache(): void {
  moduleCache = new WeakMap();
}

export type {
  CatalogLoader,
  CatalogModule,
  GetTOptions,
  NextLocaleConfig,
  ProxyOptions,
} from './types';
export { LOCALE_HEADER } from './types';

/** Locale set by the proxy middleware. `undefined` when the proxy didn't run. */
export async function getRequestLocale(): Promise<Locale | undefined> {
  const { headers } = await import('next/headers');
  const h = await headers();
  return h.get(LOCALE_HEADER) ?? undefined;
}

/**
 * Translator bound to `locale`.
 *
 * Exactly one of `options.module` or `options.load` is required:
 * - `module`: pass the generated catalog module (`import * as catalogModule from '<outDir>/index.ts'`).
 *   Calls are memoized per (module, locale) so each locale is loaded at most once per process.
 * - `load`: custom loader for KV, Edge Config, or other non-bundled sources.
 */
export async function getT(locale: Locale, options: GetTOptions = {}): Promise<Translator> {
  assertVersionHandshake();

  const { module: catalogModule, load, fallback } = options;

  if (!catalogModule && !load) {
    throw new Error(
      '[autotranslate] getT requires either a catalog module or a custom loader.\n' +
        "Add `import * as catalogModule from '<outDir>/index.ts'` " +
        '(generated by autotranslate extract / the dev loop)\n' +
        'and pass it as `getT(locale, { module: catalogModule })`.',
    );
  }

  function loadLocale(loc: Locale): Promise<Catalog> {
    if (catalogModule) {
      let localeMap = moduleCache.get(catalogModule);
      if (!localeMap) {
        localeMap = new Map();
        moduleCache.set(catalogModule, localeMap);
      }
      let promise = localeMap.get(loc);
      if (!promise) {
        promise = catalogModule.loadCatalog(loc);
        localeMap.set(loc, promise);
      }
      return promise;
    }
    return Promise.resolve(load!(loc));
  }

  const [catalog, fallbackCatalog] = await Promise.all([
    loadLocale(locale),
    fallback ? loadLocale(fallback) : Promise.resolve(undefined),
  ]);

  return createTranslator({
    locale,
    catalog,
    ...(fallbackCatalog ? { fallback: fallbackCatalog } : {}),
  });
}
