import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, join, relative } from 'node:path';
import { isMissing } from '../catalog';
import type { ResolvedConfig } from '../types';

export interface GenerateTypesResult {
  readonly path: string;
  readonly keyCount: number;
}

/**
 * Emit a `.d.ts` that augments `@autotranslate/react`'s `AutotranslateCatalog`
 * with the literal catalog keys.
 */
export async function generateTypes(resolved: ResolvedConfig): Promise<GenerateTypesResult> {
  const { config, outDir } = resolved;
  const sourcePath = join(outDir, `${config.source}.json`);
  const catalog = await readCatalog(sourcePath);
  const keys = Object.keys(catalog).sort();

  const target = join(outDir, 'types.d.ts');
  const banner = '// Generated by `autotranslate generate-types`. Do not edit.';
  const body =
    keys.length === 0
      ? `${banner}\nexport {};\n`
      : `${banner}
import '@autotranslate/react';

declare module '@autotranslate/react' {
  interface AutotranslateCatalog {
${keys.map((k) => `    ${JSON.stringify(k)}: true;`).join('\n')}
  }
}
`;

  await mkdir(dirname(target), { recursive: true });
  await writeFile(target, body, 'utf8');
  return { path: target, keyCount: keys.length };
}

async function readCatalog(path: string): Promise<Record<string, unknown>> {
  try {
    const raw = await readFile(path, 'utf8');
    return JSON.parse(raw) as Record<string, unknown>;
  } catch (error) {
    if (isMissing(error)) {
      throw new Error(`Source catalog not found at ${path}. Run \`autotranslate extract\` first.`);
    }
    throw error;
  }
}

export function relativeFromCwd(absolute: string, cwd: string): string {
  const rel = relative(cwd, absolute);
  return rel || absolute;
}
