import { mkdir, stat, writeFile } from 'node:fs/promises';
import { dirname, join, relative } from 'node:path';
import { isMissing, readChunkedCatalog } from '../catalog';
import type { ResolvedConfig } from '../types';

export interface GenerateTypesResult {
  readonly path: string;
  readonly keyCount: number;
}

/**
 * Emit a `.d.ts` augmenting `@autotranslate/core`'s `AutotranslateCatalog`
 * with the literal catalog keys. `useT`, `t`, and zod integrations all read
 * from the same interface.
 */
export async function generateTypes(resolved: ResolvedConfig): Promise<GenerateTypesResult> {
  const { config, outDir } = resolved;
  const sourceDir = join(outDir, config.source);
  const flatPath = join(outDir, `${config.source}.json`);

  if (!(await pathExists(sourceDir)) && !(await pathExists(flatPath))) {
    throw new Error(
      `Source catalog not found at ${sourceDir}. Run \`autotranslate extract\` first.`,
    );
  }

  const catalog = await readChunkedCatalog(outDir, config.source);
  const keys = Object.keys(catalog).sort();

  const target = join(outDir, 'types.d.ts');
  const banner = '// Generated by `autotranslate generate-types`. Do not edit.';
  const body =
    keys.length === 0
      ? `${banner}\nexport {};\n`
      : `${banner}
import '@autotranslate/core';

declare module '@autotranslate/core' {
  interface AutotranslateCatalog {
${keys.map((k) => `    ${JSON.stringify(k)}: true;`).join('\n')}
  }
}
`;

  await mkdir(dirname(target), { recursive: true });
  await writeFile(target, body, 'utf8');
  return { path: target, keyCount: keys.length };
}

async function pathExists(path: string): Promise<boolean> {
  try {
    await stat(path);
    return true;
  } catch (error) {
    if (isMissing(error)) return false;
    throw error;
  }
}

export function relativeFromCwd(absolute: string, cwd: string): string {
  const rel = relative(cwd, absolute);
  return rel || absolute;
}
