// Generated by `autotranslate generate-types`. Do not edit.
import '@autotranslate/core';

declare module '@autotranslate/core' {
  interface AutotranslateCatalog {
    "Language": true;
    "t.0abb79a3c869": true;
    "t.0d8d2b86f9f5": true;
    "t.2e7b1e1321df": true;
    "t.6118f56a847f": true;
    "t.6259fdea983c": true;
    "t.637bae00ce98": true;
    "t.7953d769b7bb": true;
    "t.84977a8aeaf2": true;
    "t.8e24c92ab08d": true;
    "t.9243329a8ed9": true;
    "t.9c674cc7f68e": true;
    "t.abd85420b6a3": true;
    "t.b810cea94026": true;
    "t.bb631215c8d2": true;
    "t.c0fa0adcad91": true;
    "t.c8f94126cad3": true;
    "t.d6c5ecf91d89": true;
  }
}
