// Generated by `autotranslate generate-types`. Do not edit.
import '@autotranslate/core';

declare module '@autotranslate/core' {
  interface AutotranslateCatalog {
    "Language": true;
    "t.0abb79a3c869": true;
    "t.0d8d2b86f9f5": true;
    "t.2e7b1e1321df": true;
    "t.308e1e158910": true;
    "t.42e1eb39224c": true;
    "t.45c4fb905e9a": true;
    "t.637bae00ce98": true;
    "t.7953d769b7bb": true;
    "t.7fefb6793f27": true;
    "t.84977a8aeaf2": true;
    "t.8e24c92ab08d": true;
    "t.93875cbc1048": true;
    "t.9c674cc7f68e": true;
    "t.9f6cef8f1058": true;
    "t.bb631215c8d2": true;
    "t.c0fa0adcad91": true;
    "t.c8f94126cad3": true;
    "t.d6c5ecf91d89": true;
    "t.f8b919250b36": true;
    "t.fa54d87ce383": true;
    "{count, plural, one {Clicked 1 time} other {Clicked # times}}": true;
  }
}
