import { mkdir, mkdtemp, readFile, stat, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { describe, expect, it } from 'vitest';
import { writeCatalogModule } from './catalog-module';

/** Create a temp dir with a couple of locale bucket files and return its path. */
async function makeFixture(): Promise<string> {
  const outDir = await mkdtemp(join(tmpdir(), 'autotranslate-catalog-module-'));

  await mkdir(join(outDir, 'en'), { recursive: true });
  await writeFile(join(outDir, 'en', '0.json'), '{"t.abc": "Hello"}\n', 'utf8');
  await writeFile(join(outDir, 'en', 'f.json'), '{"t.xyz": "World"}\n', 'utf8');

  await mkdir(join(outDir, 'es'), { recursive: true });
  await writeFile(join(outDir, 'es', '0.json'), '{"t.abc": "Hola"}\n', 'utf8');
  await writeFile(join(outDir, 'es', 'f.json'), '{"t.xyz": "Mundo"}\n', 'utf8');

  return outDir;
}

describe('writeCatalogModule', () => {
  it('emits the correct module for a two-locale fixture', async () => {
    const outDir = await makeFixture();
    const result = await writeCatalogModule(outDir, 'en', ['en', 'es']);

    expect(result.written).toBe(true);

    const text = await readFile(join(outDir, 'index.ts'), 'utf8');

    expect(text).toMatchInlineSnapshot(`
      "// .translations/index.ts - GENERATED by autotranslate. Do not edit.
      import type { Catalog, Locale } from '@autotranslate/core';

      export const source = 'en' as const;
      export const locales = ['en', 'es'] as const;

      const chunks: Record<string, ReadonlyArray<() => Promise<{ default: Catalog }>>> = {
        en: [() => import('./en/0.json') as Promise<{ default: Catalog }>, () => import('./en/f.json') as Promise<{ default: Catalog }>],
        es: [() => import('./es/0.json') as Promise<{ default: Catalog }>, () => import('./es/f.json') as Promise<{ default: Catalog }>],
      };

      export async function loadCatalog(locale: Locale): Promise<Catalog> {
        const parts = await Promise.all((chunks[locale] ?? []).map((load) => load()));
        return Object.assign({}, ...parts.map((m) => m.default));
      }
      "
    `);
  });

  it('puts source first and sorts targets alphabetically', async () => {
    const outDir = await mkdtemp(join(tmpdir(), 'autotranslate-catalog-module-'));
    await mkdir(join(outDir, 'en'), { recursive: true });
    await writeFile(join(outDir, 'en', '0.json'), '{}', 'utf8');
    await mkdir(join(outDir, 'fr'), { recursive: true });
    await writeFile(join(outDir, 'fr', '0.json'), '{}', 'utf8');
    await mkdir(join(outDir, 'de'), { recursive: true });
    await writeFile(join(outDir, 'de', '0.json'), '{}', 'utf8');

    await writeCatalogModule(outDir, 'en', ['fr', 'en', 'de']);
    const text = await readFile(join(outDir, 'index.ts'), 'utf8');

    // en (source) must come before de and fr; de before fr alphabetically.
    const localesLine = text.split('\n').find((l) => l.startsWith('export const locales'));
    expect(localesLine).toBe("export const locales = ['en', 'de', 'fr'] as const;");
  });

  it('skips a locale that has no bucket files on disk', async () => {
    const outDir = await mkdtemp(join(tmpdir(), 'autotranslate-catalog-module-'));
    await mkdir(join(outDir, 'en'), { recursive: true });
    await writeFile(join(outDir, 'en', '0.json'), '{}', 'utf8');
    // 'ja' locale directory does not exist yet

    await writeCatalogModule(outDir, 'en', ['en', 'ja']);
    const text = await readFile(join(outDir, 'index.ts'), 'utf8');

    expect(text).toContain("export const locales = ['en', 'ja'] as const;");
    expect(text).toContain("en: [() => import('./en/0.json') as Promise<{ default: Catalog }>]");
    expect(text).not.toContain('ja:');
  });

  it('returns { written: false } on a second identical call (idempotent)', async () => {
    const outDir = await makeFixture();

    const first = await writeCatalogModule(outDir, 'en', ['en', 'es']);
    expect(first.written).toBe(true);

    const second = await writeCatalogModule(outDir, 'en', ['en', 'es']);
    expect(second.written).toBe(false);
  });

  it('does not update the file mtime when content is unchanged', async () => {
    const outDir = await makeFixture();
    await writeCatalogModule(outDir, 'en', ['en', 'es']);

    const mtimeBefore = (await stat(join(outDir, 'index.ts'))).mtimeMs;

    // Wait 5 ms so an unnecessary write would produce a detectably later mtime.
    await new Promise((r) => setTimeout(r, 5));

    await writeCatalogModule(outDir, 'en', ['en', 'es']);
    const mtimeAfter = (await stat(join(outDir, 'index.ts'))).mtimeMs;

    expect(mtimeAfter).toBe(mtimeBefore);
  });

  it('rewrites and returns { written: true } when content changes', async () => {
    const outDir = await makeFixture();
    await writeCatalogModule(outDir, 'en', ['en', 'es']);

    await writeFile(join(outDir, 'es', 'a.json'), '{}', 'utf8');

    const result = await writeCatalogModule(outDir, 'en', ['en', 'es']);
    expect(result.written).toBe(true);

    const text = await readFile(join(outDir, 'index.ts'), 'utf8');
    expect(text).toContain("() => import('./es/a.json') as Promise<{ default: Catalog }>");
  });

  it('does not write when called a third time after an intervening rewrite', async () => {
    const outDir = await makeFixture();

    await writeCatalogModule(outDir, 'en', ['en', 'es']);

    await writeFile(join(outDir, 'es', 'b.json'), '{}', 'utf8');
    const second = await writeCatalogModule(outDir, 'en', ['en', 'es']);
    expect(second.written).toBe(true);

    const third = await writeCatalogModule(outDir, 'en', ['en', 'es']);
    expect(third.written).toBe(false);
  });
});
