import { mkdir, readdir, readFile, stat, writeFile } from 'node:fs/promises';
import { join, relative } from 'node:path';
import type { Locale } from '@autotranslate/core';

export interface WriteCatalogModuleResult {
  readonly written: boolean;
}

/**
 * Enumerate all `.json` files under a directory, recursively, sorted.
 * Returns absolute paths. Returns `[]` when the directory does not exist.
 */
async function listJsonFilesRecursive(dir: string): Promise<string[]> {
  let isDir = false;
  try {
    isDir = (await stat(dir)).isDirectory();
  } catch {
    // ENOENT or similar - treat as absent
  }
  if (!isDir) return [];

  const out: string[] = [];
  const entries = await readdir(dir, { withFileTypes: true });
  for (const entry of entries) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) {
      out.push(...(await listJsonFilesRecursive(full)));
    } else if (entry.isFile() && entry.name.endsWith('.json')) {
      out.push(full);
    }
  }
  out.sort();
  return out;
}

/**
 * Build the text of the generated catalog module for the given outDir.
 *
 * - `source` is listed first in `locales`, then targets sorted alphabetically.
 * - Within each locale, chunk import paths are sorted.
 * - Only files that actually exist on disk are included.
 */
async function buildModuleText(
  outDir: string,
  source: Locale,
  locales: ReadonlyArray<Locale>,
): Promise<string> {
  const targets = [...locales].filter((l) => l !== source).sort();
  const orderedLocales = [source, ...targets];

  const chunkLines: string[] = [];
  for (const locale of orderedLocales) {
    const localeDir = join(outDir, locale);
    const files = await listJsonFilesRecursive(localeDir);
    if (files.length === 0) continue;

    const imports = files.map((f) => {
      // Import specifiers need forward slashes even on Windows. The cast stops
      // TypeScript widening the inferred JSON literal type in the emitted file.
      const rel = relative(outDir, f).replace(/\\/g, '/');
      return `() => import('./${rel}') as Promise<{ default: Catalog }>`;
    });

    chunkLines.push(`  ${locale}: [${imports.join(', ')}],`);
  }

  const localesLiteral = orderedLocales.map((l) => `'${l}'`).join(', ');
  const chunksBlock = chunkLines.join('\n');

  return [
    `// .translations/index.ts - GENERATED by autotranslate. Do not edit.`,
    `import type { Catalog, Locale } from '@autotranslate/core';`,
    ``,
    `export const source = '${source}' as const;`,
    `export const locales = [${localesLiteral}] as const;`,
    ``,
    `const chunks: Record<string, ReadonlyArray<() => Promise<{ default: Catalog }>>> = {`,
    chunksBlock,
    `};`,
    ``,
    `export async function loadCatalog(locale: Locale): Promise<Catalog> {`,
    `  const parts = await Promise.all((chunks[locale] ?? []).map((load) => load()));`,
    `  return Object.assign({}, ...parts.map((m) => m.default));`,
    `}`,
    ``,
  ].join('\n');
}

/**
 * Write `<outDir>/index.ts` - the generated catalog module.
 *
 * Enumerates actual bucket JSON files on disk under `<outDir>/<locale>/`
 * to build the `chunks` record. The write is skipped when the content is
 * identical to what is already on disk (idempotent, avoids HMR churn).
 *
 * @returns `{ written: true }` when the file was (re)written, `{ written: false }` when skipped.
 */
export async function writeCatalogModule(
  outDir: string,
  source: Locale,
  locales: ReadonlyArray<Locale>,
): Promise<WriteCatalogModuleResult> {
  const text = await buildModuleText(outDir, source, locales);
  const outFile = join(outDir, 'index.ts');

  try {
    const existing = await readFile(outFile, 'utf8');
    if (existing === text) return { written: false };
  } catch {
    // File absent or unreadable - proceed to write.
  }

  await mkdir(outDir, { recursive: true });
  await writeFile(outFile, text, 'utf8');
  return { written: true };
}
