import { mkdir, readdir, readFile, stat, writeFile } from 'node:fs/promises';
import { join, relative } from 'node:path';
import type { Locale } from '@autotranslate/core';

export interface WriteCatalogModuleResult {
  readonly written: boolean;
}

/**
 * Enumerate all `.json` files under a directory, recursively, sorted.
 * Returns absolute paths. Returns `[]` when the directory does not exist.
 */
async function listJsonFilesRecursive(dir: string): Promise<string[]> {
  let isDir = false;
  try {
    isDir = (await stat(dir)).isDirectory();
  } catch {
    // ENOENT or similar - treat as absent
  }
  if (!isDir) return [];

  const out: string[] = [];
  const entries = await readdir(dir, { withFileTypes: true });
  for (const entry of entries) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) {
      out.push(...(await listJsonFilesRecursive(full)));
    } else if (entry.isFile() && entry.name.endsWith('.json')) {
      out.push(full);
    }
  }
  out.sort();
  return out;
}

/**
 * Build the text of the generated catalog module for the given outDir.
 *
 * - `source` is listed first in `locales`, then targets sorted alphabetically.
 * - Within each locale, chunk import paths are sorted.
 * - Only files that actually exist on disk are included.
 */
async function buildModuleText(
  outDir: string,
  source: Locale,
  locales: ReadonlyArray<Locale>,
): Promise<string> {
  const targets = [...locales].filter((l) => l !== source).sort();
  const orderedLocales = [source, ...targets];

  const specifiers = new Map<string, ReadonlyArray<string>>();
  for (const locale of orderedLocales) {
    const files = await listJsonFilesRecursive(join(outDir, locale));
    if (files.length === 0) continue;
    // Import specifiers need forward slashes even on Windows.
    specifiers.set(
      locale,
      files.map((f) => `./${relative(outDir, f).replace(/\\/g, '/')}`),
    );
  }

  return renderCatalogModule(source, orderedLocales, specifiers);
}

/**
 * Render the catalog module from an explicit chunk map. Exported so the git
 * merge driver can re-emit the file from the union of two branches' chunks
 * instead of leaving conflict markers in generated TypeScript.
 */
export function renderCatalogModule(
  source: Locale,
  orderedLocales: ReadonlyArray<Locale>,
  specifiersByLocale: ReadonlyMap<string, ReadonlyArray<string>>,
): string {
  const chunkLines: string[] = [];
  for (const locale of orderedLocales) {
    const specifiers = specifiersByLocale.get(locale);
    if (!specifiers || specifiers.length === 0) continue;
    // One import per line, sorted. This file is committed, so two branches
    // that each add a string land in different bucket files - on a single
    // packed line that is one conflict, line-per-import it merges cleanly.
    chunkLines.push(`  ${locale}: [`);
    for (const specifier of specifiers) {
      // The cast stops TypeScript widening the inferred JSON literal type.
      chunkLines.push(`    () => import('${specifier}') as Promise<{ default: Catalog }>,`);
    }
    chunkLines.push(`  ],`);
  }

  const localesLiteral = orderedLocales.map((l) => `'${l}'`).join(', ');
  const chunksBlock = chunkLines.join('\n');

  return [
    `// .translations/index.ts - GENERATED by autotranslate. Do not edit.`,
    `import type { Catalog, Locale } from '@autotranslate/core';`,
    ``,
    `export const source = '${source}' as const;`,
    `export const locales = [${localesLiteral}] as const;`,
    ``,
    `const chunks: Record<string, ReadonlyArray<() => Promise<{ default: Catalog }>>> = {`,
    chunksBlock,
    `};`,
    ``,
    `/**`,
    ` * The catalog for a locale, or an empty one for the source locale.`,
    ` *`,
    ` * Source-locale entries are never consulted: \`<T>\` falls back to its own`,
    ` * children and \`t()\` falls back to the key, both of which ARE the source`,
    ` * text. Loading the source catalog therefore buys nothing and costs a lot -`,
    ` * in a server-rendered app it is serialised into the payload of every`,
    ` * navigation, which for a mid-sized app is hundreds of kilobytes per page.`,
    ` */`,
    `export async function loadCatalog(locale: Locale): Promise<Catalog> {`,
    `  if (locale === source) return {};`,
    `  const parts = await Promise.all((chunks[locale] ?? []).map((load) => load()));`,
    `  return Object.assign({}, ...parts.map((m) => m.default));`,
    `}`,
    ``,
  ].join('\n');
}

/**
 * Write `<outDir>/index.ts` - the generated catalog module.
 *
 * Enumerates actual bucket JSON files on disk under `<outDir>/<locale>/`
 * to build the `chunks` record. The write is skipped when the content is
 * identical to what is already on disk (idempotent, avoids HMR churn).
 *
 * @returns `{ written: true }` when the file was (re)written, `{ written: false }` when skipped.
 */
export async function writeCatalogModule(
  outDir: string,
  source: Locale,
  locales: ReadonlyArray<Locale>,
): Promise<WriteCatalogModuleResult> {
  const text = await buildModuleText(outDir, source, locales);
  const outFile = join(outDir, 'index.ts');

  try {
    const existing = await readFile(outFile, 'utf8');
    if (existing === text) return { written: false };
  } catch {
    // File absent or unreadable - proceed to write.
  }

  await mkdir(outDir, { recursive: true });
  await writeFile(outFile, text, 'utf8');
  return { written: true };
}
