import { mkdtemp, readFile, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { describe, expect, it } from 'vitest';
import {
  classifyPath,
  mergeCatalog,
  mergeCatalogModule,
  mergeState,
  runMergeDriver,
} from './merge';

function catalogModule(locales: string[], chunks: Record<string, string[]>): string {
  const body = Object.entries(chunks)
    .map(
      ([locale, files]) =>
        `  ${locale}: [\n${files
          .map((f) => `    () => import('${f}') as Promise<{ default: Catalog }>,`)
          .join('\n')}\n  ],`,
    )
    .join('\n');
  return [
    `// .translations/index.ts - GENERATED by autotranslate. Do not edit.`,
    `import type { Catalog, Locale } from '@autotranslate/core';`,
    ``,
    `export const source = 'en' as const;`,
    `export const locales = [${locales.map((l) => `'${l}'`).join(', ')}] as const;`,
    ``,
    `const chunks: Record<string, ReadonlyArray<() => Promise<{ default: Catalog }>>> = {`,
    body,
    `};`,
    ``,
    `export async function loadCatalog(locale: Locale): Promise<Catalog> {`,
    `  const parts = await Promise.all((chunks[locale] ?? []).map((load) => load()));`,
    `  return Object.assign({}, ...parts.map((m) => m.default));`,
    `}`,
    ``,
  ].join('\n');
}

describe('mergeCatalog', () => {
  it('unions keys added on both sides', () => {
    const { merged, contested } = mergeCatalog({ a: 'A' }, { a: 'A', b: 'B' }, { a: 'A', c: 'C' });
    expect(merged).toEqual({ a: 'A', b: 'B', c: 'C' });
    expect(contested).toEqual([]);
  });

  it('takes a one-sided edit', () => {
    expect(mergeCatalog({ a: 'A' }, { a: 'A2' }, { a: 'A' }).merged).toEqual({ a: 'A2' });
    expect(mergeCatalog({ a: 'A' }, { a: 'A' }, { a: 'A2' }).merged).toEqual({ a: 'A2' });
  });

  it('honours a one-sided deletion', () => {
    expect(mergeCatalog({ a: 'A', b: 'B' }, { a: 'A' }, { a: 'A', b: 'B' }).merged).toEqual({
      a: 'A',
    });
  });

  it('is not confused by both sides making the same edit', () => {
    const { merged, contested } = mergeCatalog({ a: 'A' }, { a: 'A2' }, { a: 'A2' });
    expect(merged).toEqual({ a: 'A2' });
    expect(contested).toEqual([]);
  });

  it('resolves a two-sided edit deterministically and flags it', () => {
    const { merged, contested } = mergeCatalog({ a: 'A' }, { a: 'ours' }, { a: 'theirs' });
    expect(merged).toEqual({ a: 'ours' });
    expect(contested).toEqual(['a']);
  });

  it('lets a deletion win over a concurrent edit', () => {
    const { merged, contested } = mergeCatalog({ a: 'A' }, {}, { a: 'theirs' });
    expect(merged).toEqual({});
    expect(contested).toEqual(['a']);
  });

  it('merges structured tree entries by key, not by line', () => {
    const tree = [{ type: 'text', value: 'Hola' }];
    const { merged } = mergeCatalog({}, { 't.aaa': tree }, { 't.bbb': tree });
    expect(Object.keys(merged).sort()).toEqual(['t.aaa', 't.bbb']);
  });

  it('emits keys in sorted order for stable diffs', () => {
    const { merged } = mergeCatalog({}, { c: '1', a: '2' }, { b: '3' });
    expect(Object.keys(merged)).toEqual(['a', 'b', 'c']);
  });
});

describe('mergeState', () => {
  it('unions hashes recorded on both sides', () => {
    const { merged } = mergeState(
      { version: 1, keys: { a: 'h1' } },
      { version: 1, keys: { a: 'h1', b: 'h2' } },
      { version: 1, keys: { a: 'h1', c: 'h3' } },
    );
    expect(merged).toEqual({ version: 1, keys: { a: 'h1', b: 'h2', c: 'h3' } });
  });

  it('drops a key both sides retranslated so the next run redoes it', () => {
    const { merged, contested } = mergeState(
      { version: 1, keys: { a: 'base' } },
      { version: 1, keys: { a: 'ours' } },
      { version: 1, keys: { a: 'theirs' } },
    );
    // Omitted from state -> `translate` sees no recorded hash and refetches
    // this one key, rather than trusting an arbitrary winner.
    expect(merged).toEqual({ version: 1, keys: {} });
    expect(contested).toEqual(['a']);
  });

  it('keeps a key when only one side changed it', () => {
    const { merged, contested } = mergeState(
      { version: 1, keys: { a: 'base' } },
      { version: 1, keys: { a: 'ours' } },
      { version: 1, keys: { a: 'base' } },
    );
    expect(merged).toEqual({ version: 1, keys: { a: 'ours' } });
    expect(contested).toEqual([]);
  });
});

describe('mergeCatalogModule', () => {
  it('unions chunk imports added on both sides', () => {
    const ours = catalogModule(['en', 'es'], {
      en: ['./en/a.json', './en/b.json'],
      es: ['./es/a.json', './es/b.json'],
    });
    const theirs = catalogModule(['en', 'es'], {
      en: ['./en/a.json', './en/c.json'],
      es: ['./es/a.json', './es/c.json'],
    });

    const merged = mergeCatalogModule(ours, theirs);

    expect(merged).not.toContain('<<<<<<<');
    const enImports = merged
      .split('\n')
      .filter((l) => l.includes("import('./en/"))
      .map((l) => (/import\('([^']+)'\)/.exec(l) as RegExpExecArray)[1]);
    expect(enImports).toEqual(['./en/a.json', './en/b.json', './en/c.json']);
  });

  it('keeps locales introduced by only one side', () => {
    const ours = catalogModule(['en', 'es'], { en: ['./en/a.json'], es: ['./es/a.json'] });
    const theirs = catalogModule(['en', 'fr'], { en: ['./en/a.json'], fr: ['./fr/a.json'] });

    const merged = mergeCatalogModule(ours, theirs);

    expect(merged).toContain('es: [');
    expect(merged).toContain('fr: [');
    expect(merged).toContain("locales = ['en', 'es', 'fr']");
  });

  it('falls back to the other side when one is unparseable', () => {
    const ours = catalogModule(['en'], { en: ['./en/a.json'] });
    expect(mergeCatalogModule(ours, 'not a catalog module')).toBe(ours);
    expect(mergeCatalogModule('not a catalog module', ours)).toBe(ours);
  });
});

describe('classifyPath', () => {
  it('recognises state, manifest, module and catalog files', () => {
    expect(classifyPath('.translations/.state/es/a.json')).toBe('state');
    expect(classifyPath('.translations/.meta.json')).toBe('manifest');
    expect(classifyPath('.translations/index.ts')).toBe('module');
    expect(classifyPath('.translations/es/a.json')).toBe('catalog');
    expect(classifyPath('src/App.tsx')).toBeUndefined();
  });

  it('handles Windows separators', () => {
    expect(classifyPath('.translations\\.state\\es\\a.json')).toBe('state');
  });
});

describe('runMergeDriver', () => {
  it('writes the merged catalog back over `ours` and never leaves markers', async () => {
    const dir = await mkdtemp(join(tmpdir(), 'autotranslate-merge-'));
    const base = join(dir, 'base.json');
    const ours = join(dir, 'ours.json');
    const theirs = join(dir, 'theirs.json');
    await writeFile(base, JSON.stringify({ a: 'A' }), 'utf8');
    await writeFile(ours, JSON.stringify({ a: 'A', b: 'B' }), 'utf8');
    await writeFile(theirs, JSON.stringify({ a: 'A', c: 'C' }), 'utf8');

    const result = await runMergeDriver({
      basePath: base,
      oursPath: ours,
      theirsPath: theirs,
      filePath: '.translations/es/a.json',
    });

    const written = await readFile(ours, 'utf8');
    expect(result.kind).toBe('catalog');
    expect(written).not.toContain('<<<<<<<');
    expect(JSON.parse(written)).toEqual({ a: 'A', b: 'B', c: 'C' });
    expect(written.endsWith('\n')).toBe(true);
  });

  it('applies state semantics to state files', async () => {
    const dir = await mkdtemp(join(tmpdir(), 'autotranslate-merge-'));
    const base = join(dir, 'base.json');
    const ours = join(dir, 'ours.json');
    const theirs = join(dir, 'theirs.json');
    await writeFile(base, JSON.stringify({ version: 1, keys: { a: 'base' } }), 'utf8');
    await writeFile(ours, JSON.stringify({ version: 1, keys: { a: 'ours' } }), 'utf8');
    await writeFile(theirs, JSON.stringify({ version: 1, keys: { a: 'theirs' } }), 'utf8');

    const result = await runMergeDriver({
      basePath: base,
      oursPath: ours,
      theirsPath: theirs,
      filePath: '.translations/.state/es/a.json',
    });

    expect(result.kind).toBe('state');
    expect(result.contested).toEqual(['a']);
    expect(JSON.parse(await readFile(ours, 'utf8'))).toEqual({ version: 1, keys: {} });
  });

  it('treats an absent ancestor as an empty file', async () => {
    const dir = await mkdtemp(join(tmpdir(), 'autotranslate-merge-'));
    const ours = join(dir, 'ours.json');
    const theirs = join(dir, 'theirs.json');
    await writeFile(ours, JSON.stringify({ a: 'A' }), 'utf8');
    await writeFile(theirs, JSON.stringify({ b: 'B' }), 'utf8');

    await runMergeDriver({
      basePath: join(dir, 'missing.json'),
      oursPath: ours,
      theirsPath: theirs,
      filePath: '.translations/es/a.json',
    });

    expect(JSON.parse(await readFile(ours, 'utf8'))).toEqual({ a: 'A', b: 'B' });
  });
});
