import { type Catalog, createTranslator, type Locale } from '@autotranslate/core';
import { withTranslator } from '@autotranslate/core/standalone';
import enFallback from './catalog/en.json' with { type: 'json' };

/**
 * The generated catalog module emitted by `autotranslate extract` at
 * `<outDir>/index.ts`. Import it statically so the bundler can code-split
 * catalogs per locale.
 *
 * Mirrors the `CatalogModule` shape from `@autotranslate/next` - defined
 * locally here so `@autotranslate/zod/next` has no runtime dep on that package.
 */
export interface CatalogModule {
  readonly source: Locale;
  readonly locales: ReadonlyArray<Locale>;
  loadCatalog(locale: Locale): Promise<Catalog>;
}

export type CatalogLoader = (locale: Locale) => Promise<Catalog> | Catalog;

export interface NextRequestTranslatorOptions {
  /** Override the resolved locale. Defaults to `getRequestLocale()` from `@autotranslate/next`. */
  readonly locale?: Locale;
  /**
   * Generated catalog module from `<outDir>/index.ts`.
   * Exactly one of `module` or `load` is required.
   *
   * ```ts
   * import * as catalogModule from '../../.translations';
   * return withRequestTranslator(fn, { module: catalogModule });
   * ```
   */
  readonly module?: CatalogModule;
  /**
   * Custom catalog loader - use for KV, Edge Config, or other non-bundled
   * sources. Exactly one of `module` or `load` is required.
   */
  readonly load?: CatalogLoader;
  /** Locale used when neither header nor `locale` option is set. */
  readonly defaultLocale?: Locale;
}

/**
 * Wrap a Next.js Server Action / route handler so the bundled zod error map
 * sees a translator scoped to the request locale.
 *
 * Exactly one of `options.module` or `options.load` is required:
 * - `module`: pass the generated catalog module (`import * as catalogModule from '<outDir>/index.ts'`).
 * - `load`: custom loader for KV, Edge Config, or other non-bundled sources.
 *
 * ```ts
 * import { withRequestTranslator } from '@autotranslate/zod/next';
 * import * as catalogModule from '../../.translations';
 *
 * export async function signUp(formData: FormData) {
 *   return withRequestTranslator(async () => userSchema.parseAsync(...), {
 *     module: catalogModule,
 *   });
 * }
 * ```
 */
export async function withRequestTranslator<R>(
  fn: () => R | Promise<R>,
  options: NextRequestTranslatorOptions = {},
): Promise<R> {
  const { module: catalogModule, load } = options;

  if (!catalogModule && !load) {
    throw new Error(
      '[autotranslate/zod] withRequestTranslator requires either a catalog module or a custom loader.\n' +
        "Add `import * as catalogModule from '<outDir>/index.ts'` " +
        '(generated by `autotranslate extract` or the dev loop)\n' +
        'and pass it as `withRequestTranslator(fn, { module: catalogModule })`.',
    );
  }

  const locale = options.locale ?? (await resolveLocale(options.defaultLocale ?? 'en'));
  const catalog = await loadCatalog(locale, catalogModule, load);
  const translator = createTranslator({ locale, catalog, fallback: enFallback as Catalog });
  return withTranslator(translator, async () => fn());
}

async function resolveLocale(fallback: Locale): Promise<Locale> {
  const next = await import('@autotranslate/next');
  const fromHeader = await next.getRequestLocale();
  return fromHeader ?? fallback;
}

async function loadCatalog(
  locale: Locale,
  catalogModule: CatalogModule | undefined,
  load: CatalogLoader | undefined,
): Promise<Catalog> {
  if (catalogModule) return catalogModule.loadCatalog(locale);
  if (load) return load(locale);
  return {};
}
